added simple pytest, changed main.yml, added Badge

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -44,14 +44,15 @@ jobs:
           python --version
 
       # execute multiple commands to install pygame
-      - name: Install pygame
+      - name: Install pip, pygame and pytest
         run: |
           python -m pip install --upgrade pip
           pip --version
           pip install pygame
+          pip install pytest
 
-      # Run the main.py script, exit with error if it fails
+      # Run the main.py script, exit with error if it fails (python main.py)
+      # run tests from root of the directory (test folder)
       - name: Run main.py
         run: |
-          python main.py || exit 1
-        timeout-minutes: 1
+          pytest -s -v  || exit 1
